export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header style={{ backgroundColor: 'lightblue', padding: '10px' }}>
        Header
      </header>
      <body>{children}</body>
      <footer style={{ backgroundColor: 'lightgreen', padding: '10px' }}>
        Footer
      </footer>
    </html>
  )
}
